name: Run jest tests
on: [push]
jobs:
  Jest-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.1.0
      - run: yarn
      - run: yarn test

  Jest-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.1.0
      - run: yarn
      - run: yarn test:cov
